### ISSUE TITLE
fs-base not in npm registry

### ISSUE THREAD

**Issue by maxleiko** [olegp/mcms#17]
Hi,

It impossible for me to start MCMS. I've tried with NodeJS and Ringo, both fail.

That's for NodeJS (after npm install) and using node 0.10.22  

``` sh
➜  mcms git:(master) ✗ node lib/mcms.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'fs-base'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/leiko/dev/mcms_test/mcms/lib/mcms.js:2:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

And that's for Ringo (after installing what's asked in the 'Get Started') and using version 0.10  

``` sh
➜  mcms git:(master) ✗ ringo lib/mcms.js 
Cannot find resource 
function (request) {
    var uri = request.pathInfo.substr(1);
    if (!uri.indexOf("static")) {
        return serve(uri);
    }
    var name = friendly(uri) || "index";
    var page = load(name);
    return {status:page ? 200 : 404, headers:{"Content-Type":"text/config/log4j.properties'
    at ringo/httpserver.js:440 (init)
    at ringo/httpserver.js:524 (main)
    at /home/leiko/dev/mcms_test/mcms/lib/mcms.js:163
```

So it seems for me, that when you try to start the thing with NodeJS you use `fs-base` module which does not exist in npm registry nor in your libs.  
And with Ringo, it seems like you are returning a function to mcms() function but Ringo's httpserver expect to get a string path to their main() method.

What am I doing wrong ?

**Comment by olegp** [comment]
With Node do `npm install common-node -g' and then`common-node lib/mcms.js'

**Comment by maxleiko** [comment]
Ok thanks!

And what about RingoJS ?

**Comment by olegp** [comment]
Will look into Ringo next week when I have more time, it's possible their APIs have changed.

**Comment by maxleiko** [comment]
Appreciate the quick answers :) Thanks

**Comment by maxleiko** [comment]
Hi there,

Any news for this issue ? Did you manage to find some time to look at it ?

**Comment by olegp** [comment]
@maxleiko the commit above makes a bit of progress so that at least the server starts up. however, I now get an error when actually connecting to localhost:8080 which I'm currently pretty stumped by. I suspect it has something to do with the paths where the module is loaded from vs. where the command is run from, but that's just a guess. Can you poke around to see if you can do better?
